### ISSUE TITLE
Rollover de liens illisibles ou invisibles

### ISSUE THREAD

**Issue by hiwelo** [Archi-Strasbourg/archi-wiki#2]
Petit soucis avec les rollovers de certaines zones clicables sur cette page : 
http://www.archi-wiki.org/
**Section actualités de l'association**

![bmnpz48oo1](https://cloud.githubusercontent.com/assets/4989733/8968018/168c67a2-363b-11e5-85eb-53c22133b860.gif)

**Comment by hiwelo** [comment]
Petit soucis ici aussi : 
![zvkspjzdkp](https://cloud.githubusercontent.com/assets/4989733/8968203/0649c546-363c-11e5-9d60-2f17cfe9992d.gif)

Et là :
![gr3dy97fcr](https://cloud.githubusercontent.com/assets/4989733/8968222/187ada0c-363c-11e5-8390-6e0dd82f2ca4.gif)

Et sans doute à plein d'autres endroits d'ailleurs

**Comment by Rudloff** [comment]
Ce code ne sera plus mis à jour donc je ferme.
